kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: pg-operator-e2e
nodes:
- role: control-plane
  image: kindest/node:v1.29.0
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  # PostgreSQL port for external access during testing
  - containerPort: 30432
    hostPort: 5432
    protocol: TCP
  # Metrics and monitoring ports
  - containerPort: 30080
    hostPort: 8080
    protocol: TCP
- role: worker
  image: kindest/node:v1.29.0
- role: worker  
  image: kindest/node:v1.29.0