---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgres.silverswarm.io
  resources:
  - databases
  - postgresconnections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgres.silverswarm.io
  resources:
  - databases/finalizers
  - postgresconnections/finalizers
  verbs:
  - update
- apiGroups:
  - postgres.silverswarm.io
  resources:
  - databases/status
  - postgresconnections/status
  verbs:
  - get
  - patch
  - update
