# Consolidated user management roles for postgres.silverswarm.io resources
# This replaces the separate viewer, editor, and admin role files

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: database-viewer-role
rules:
- apiGroups:
  - postgres.silverswarm.io
  resources:
  - databases
  - postgresconnections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgres.silverswarm.io
  resources:
  - databases/status
  - postgresconnections/status
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: database-editor-role
rules:
- apiGroups:
  - postgres.silverswarm.io
  resources:
  - databases
  - postgresconnections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgres.silverswarm.io
  resources:
  - databases/status
  - postgresconnections/status
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: database-admin-role
rules:
- apiGroups:
  - postgres.silverswarm.io
  resources:
  - databases
  - postgresconnections
  verbs:
  - '*'
- apiGroups:
  - postgres.silverswarm.io
  resources:
  - databases/status
  - postgresconnections/status
  verbs:
  - get
  - update
  - patch