name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of pg-operator are you running?
      placeholder: v0.1.0
    validations:
      required: true
      
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and what you expected to happen
      placeholder: A clear and concise description of what the bug is
    validations:
      required: true
      
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Apply this configuration '...'
        2. Run command '....'
        3. See error
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide environment details
      value: |
        - Kubernetes version:
        - CloudNativePG version:
        - pg-operator version:
        - Operating System:
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Please copy and paste any relevant log output
      render: shell
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here