name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: '1.23'
  CNPG_VERSION: '1.24.4'

jobs:
  test:
    name: Unit Tests and Lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: go.sum

      # TODO: Re-enable golangci-lint after fixing controller test issues
      # - name: Install golangci-lint
      #   uses: golangci/golangci-lint-action@v4
      #   with:
      #     version: v1.64.8
      #     skip-cache: false
      #     args: --timeout=5m

      - name: Debug Go environment
        run: |
          go version
          go env GOROOT
          go env GOPATH
          go env GO111MODULE
          ls -la pkg/
          ls -la internal/controller/
          go mod download
          go mod verify
          
      - name: Run unit tests
        run: make test

      - name: Verify generated manifests
        run: |
          make generate manifests
          git diff --exit-code || (echo "Generated files are out of date. Run 'make generate manifests' and commit the changes." && exit 1)

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  e2e:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: go.sum

      - name: Create Kind cluster
        uses: helm/kind-action@v1.10.0
        with:
          version: v0.24.0
          node_image: kindest/node:v1.31.2
          cluster_name: operator-test-e2e
          config: .github/kind-config.yaml

      - name: Install CloudNativePG Operator
        run: |
          kubectl apply --server-side -f https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.24/releases/cnpg-${{ env.CNPG_VERSION }}.yaml
          kubectl wait --for=condition=Available deployment/cnpg-controller-manager -n cnpg-system --timeout=300s

      - name: Create PostgreSQL cluster
        run: |
          # Delete existing cluster if it exists to ensure fresh config
          kubectl delete -f test/e2e/manifests/postgres-cluster.yaml --ignore-not-found=true
          kubectl wait --for=delete cluster/postgres-cluster --timeout=300s || true
          kubectl apply -f test/e2e/manifests/postgres-cluster.yaml
          kubectl wait --for=condition=Ready cluster/postgres-cluster --timeout=600s
          kubectl wait --for=condition=Ready pod -l cnpg.io/cluster=postgres-cluster -n default --timeout=600s

      - name: Build and load operator image into Kind
        run: |
          docker build -t pg-operator:latest .
          kind load docker-image pg-operator:latest --name operator-test-e2e
          echo "Verifying image is loaded in Kind cluster:"
          docker exec operator-test-e2e-control-plane crictl images | grep pg-operator || echo "Image not found in Kind"

      - name: Deploy operator
        run: |
          export IMG=pg-operator:latest
          make install
          make deploy

      - name: Wait for operator to be ready
        run: |
          echo "Checking operator deployment status..."
          kubectl get deployment operator-controller-manager -n operator-system
          kubectl get pods -n operator-system
          echo "Waiting for operator to be ready (10 minutes timeout)..."
          kubectl wait --for=condition=Available deployment/operator-controller-manager -n operator-system --timeout=600s

      - name: Run e2e tests
        run: |
          export USE_EXISTING_CLUSTER=true
          export IMG=pg-operator:latest
          export KIND_CLUSTER=operator-test-e2e
          make test-e2e

      - name: Collect logs on failure
        if: failure()
        run: |
          echo "=== Operator pod status ==="
          kubectl get pods -n operator-system -o wide
          kubectl describe pods -n operator-system
          echo "=== Operator pod events ==="
          kubectl get events -n operator-system --sort-by=.metadata.creationTimestamp
          echo "=== Node resources ==="
          kubectl top nodes || echo "Metrics not available"
          kubectl describe nodes
          echo "=== Operator logs ==="
          kubectl logs -l control-plane=controller-manager -n operator-system --tail=100 || echo "No logs available yet"
          echo "=== CNPG logs ==="
          kubectl logs -l app.kubernetes.io/name=cloudnative-pg -n cnpg-system --tail=100
          echo "=== PostgreSQL cluster status ==="
          kubectl describe cluster postgres-cluster
          echo "=== PostgreSQL pod logs ==="
          kubectl logs -l cnpg.io/cluster=postgres-cluster --tail=50
