name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: '1.22'

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: go.sum

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.62.2
          skip-cache: false

      - name: Run tests
        run: make test

      - name: Verify generated manifests
        run: |
          make generate manifests
          git diff --exit-code || (echo "Generated files are out of date. Run 'make generate manifests' and commit the changes." && exit 1)

  build:
    name: Build Image
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          tags: pg-operator:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max